// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "ewallet-server-v2/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// GameBoxUsecase is an autogenerated mock type for the GameBoxUsecase type
type GameBoxUsecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *GameBoxUsecase) GetAll(ctx context.Context) ([]model.GameBox, error) {
	ret := _m.Called(ctx)

	var r0 []model.GameBox
	if rf, ok := ret.Get(0).(func(context.Context) []model.GameBox); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GameBox)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOneById provides a mock function with given fields: ctx, boxId
func (_m *GameBoxUsecase) GetOneById(ctx context.Context, boxId int64) (*model.GameBox, error) {
	ret := _m.Called(ctx, boxId)

	var r0 *model.GameBox
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.GameBox); ok {
		r0 = rf(ctx, boxId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GameBox)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, boxId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGameBoxUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewGameBoxUsecase creates a new instance of GameBoxUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGameBoxUsecase(t mockConstructorTestingTNewGameBoxUsecase) *GameBoxUsecase {
	mock := &GameBoxUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
