// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "ewallet-server-v2/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// GameAttemptRepository is an autogenerated mock type for the GameAttemptRepository type
type GameAttemptRepository struct {
	mock.Mock
}

// CreateOne provides a mock function with given fields: ctx, gameAttempt
func (_m *GameAttemptRepository) CreateOne(ctx context.Context, gameAttempt model.GameAttempt) (*model.GameAttempt, error) {
	ret := _m.Called(ctx, gameAttempt)

	var r0 *model.GameAttempt
	if rf, ok := ret.Get(0).(func(context.Context, model.GameAttempt) *model.GameAttempt); ok {
		r0 = rf(ctx, gameAttempt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GameAttempt)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.GameAttempt) error); ok {
		r1 = rf(ctx, gameAttempt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCountByWalletId provides a mock function with given fields: ctx, walletId
func (_m *GameAttemptRepository) GetCountByWalletId(ctx context.Context, walletId int64) (int64, error) {
	ret := _m.Called(ctx, walletId)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, walletId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, walletId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGameAttemptRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewGameAttemptRepository creates a new instance of GameAttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGameAttemptRepository(t mockConstructorTestingTNewGameAttemptRepository) *GameAttemptRepository {
	mock := &GameAttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
