// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RandomUtil is an autogenerated mock type for the RandomUtil type
type RandomUtil struct {
	mock.Mock
}

// StringAlphaNum provides a mock function with given fields: len
func (_m *RandomUtil) StringAlphaNum(len int) string {
	ret := _m.Called(len)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(len)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewRandomUtil interface {
	mock.TestingT
	Cleanup(func())
}

// NewRandomUtil creates a new instance of RandomUtil. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRandomUtil(t mockConstructorTestingTNewRandomUtil) *RandomUtil {
	mock := &RandomUtil{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
