// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WalletNumberFormatter is an autogenerated mock type for the WalletNumberFormatter type
type WalletNumberFormatter struct {
	mock.Mock
}

// Format provides a mock function with given fields: userId
func (_m *WalletNumberFormatter) Format(userId int64) string {
	ret := _m.Called(userId)

	var r0 string
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewWalletNumberFormatter interface {
	mock.TestingT
	Cleanup(func())
}

// NewWalletNumberFormatter creates a new instance of WalletNumberFormatter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWalletNumberFormatter(t mockConstructorTestingTNewWalletNumberFormatter) *WalletNumberFormatter {
	mock := &WalletNumberFormatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
