// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// GetParamInterface is an autogenerated mock type for the GetParamInterface type
type GetParamInterface struct {
	mock.Mock
}

// GetParamNumber provides a mock function with given fields: _a0, _a1
func (_m *GetParamInterface) GetParamNumber(_a0 *gin.Context, _a1 string) (int, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int
	if rf, ok := ret.Get(0).(func(*gin.Context, string) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGetParamInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetParamInterface creates a new instance of GetParamInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetParamInterface(t mockConstructorTestingTNewGetParamInterface) *GetParamInterface {
	mock := &GetParamInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
