// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ValidationReqBodyInterface is an autogenerated mock type for the ValidationReqBodyInterface type
type ValidationReqBodyInterface struct {
	mock.Mock
}

// ValidationReqBody provides a mock function with given fields: _a0, _a1
func (_m *ValidationReqBodyInterface) ValidationReqBody(_a0 *gin.Context, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewValidationReqBodyInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidationReqBodyInterface creates a new instance of ValidationReqBodyInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidationReqBodyInterface(t mockConstructorTestingTNewValidationReqBodyInterface) *ValidationReqBodyInterface {
	mock := &ValidationReqBodyInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
